//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1

import "k8s.io/client-go/kubernetes"

type ResourceManager struct {
	repoMgr     *RepositoryManager
	tokenMgr    *TokenManager
	artifactMgr *ArtifactManager
}

func NewResourceManager(clientset *kubernetes.Clientset, testjob TestJob) *ResourceManager {
	tokenClient := NewTokenClient(clientset, testjob.Namespace)
	tokenMgr := NewTokenManager(testjob.Spec.Tokens, tokenClient)
	repoMgr := NewRepositoryManager(testjob.Spec.Repos, tokenMgr)
	artifactMgr := NewArtifactManager()
	return &ResourceManager{
		repoMgr:     repoMgr,
		tokenMgr:    tokenMgr,
		artifactMgr: artifactMgr,
	}
}

func (m *ResourceManager) Cleanup() error {
	return m.repoMgr.Cleanup()
}
