//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1

import (
	"fmt"

	corev1 "k8s.io/api/core/v1"
)

func getMainContainerFromTmpl(tmpl TestJobTemplateSpec) (corev1.Container, error) {
	if tmpl.Main != "" {
		for _, container := range tmpl.Spec.Containers {
			if container.Name == tmpl.Main {
				return container, nil
			}
		}
		return corev1.Container{}, fmt.Errorf("kubetest: couldn't find main container name %s", tmpl.Main)
	}
	if len(tmpl.Spec.Containers) == 1 {
		return tmpl.Spec.Containers[0], nil
	}
	return corev1.Container{}, fmt.Errorf("kubetest: use multiple containers but doesn't specified main container name")
}
