// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactContainer) DeepCopyInto(out *ArtifactContainer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactContainer.
func (in *ArtifactContainer) DeepCopy() *ArtifactContainer {
	if in == nil {
		return nil
	}
	out := new(ArtifactContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactSpec) DeepCopyInto(out *ArtifactSpec) {
	*out = *in
	out.Container = in.Container
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactSpec.
func (in *ArtifactSpec) DeepCopy() *ArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactVolumeSource) DeepCopyInto(out *ArtifactVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactVolumeSource.
func (in *ArtifactVolumeSource) DeepCopy() *ArtifactVolumeSource {
	if in == nil {
		return nil
	}
	out := new(ArtifactVolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportArtifact) DeepCopyInto(out *ExportArtifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportArtifact.
func (in *ExportArtifact) DeepCopy() *ExportArtifact {
	if in == nil {
		return nil
	}
	out := new(ExportArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAppTokenSource) DeepCopyInto(out *GitHubAppTokenSource) {
	*out = *in
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAppTokenSource.
func (in *GitHubAppTokenSource) DeepCopy() *GitHubAppTokenSource {
	if in == nil {
		return nil
	}
	out := new(GitHubAppTokenSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTokenSource) DeepCopyInto(out *GitHubTokenSource) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTokenSource.
func (in *GitHubTokenSource) DeepCopy() *GitHubTokenSource {
	if in == nil {
		return nil
	}
	out := new(GitHubTokenSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSpec) DeepCopyInto(out *LogSpec) {
	*out = *in
	if in.ExtParam != nil {
		in, out := &in.ExtParam, &out.ExtParam
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSpec.
func (in *LogSpec) DeepCopy() *LogSpec {
	if in == nil {
		return nil
	}
	out := new(LogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogVolumeSource) DeepCopyInto(out *LogVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogVolumeSource.
func (in *LogVolumeSource) DeepCopy() *LogVolumeSource {
	if in == nil {
		return nil
	}
	out := new(LogVolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MainStep) DeepCopyInto(out *MainStep) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MainStep.
func (in *MainStep) DeepCopy() *MainStep {
	if in == nil {
		return nil
	}
	out := new(MainStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeSpec) DeepCopyInto(out *MergeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeSpec.
func (in *MergeSpec) DeepCopy() *MergeSpec {
	if in == nil {
		return nil
	}
	out := new(MergeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostStep) DeepCopyInto(out *PostStep) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostStep.
func (in *PostStep) DeepCopy() *PostStep {
	if in == nil {
		return nil
	}
	out := new(PostStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreStep) DeepCopyInto(out *PreStep) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreStep.
func (in *PreStep) DeepCopy() *PreStep {
	if in == nil {
		return nil
	}
	out := new(PreStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportVolumeSource) DeepCopyInto(out *ReportVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportVolumeSource.
func (in *ReportVolumeSource) DeepCopy() *ReportVolumeSource {
	if in == nil {
		return nil
	}
	out := new(ReportVolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	if in.Merge != nil {
		in, out := &in.Merge, &out.Merge
		*out = new(MergeSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySpec) DeepCopyInto(out *RepositorySpec) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySpec.
func (in *RepositorySpec) DeepCopy() *RepositorySpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryVolumeSource) DeepCopyInto(out *RepositoryVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryVolumeSource.
func (in *RepositoryVolumeSource) DeepCopy() *RepositoryVolumeSource {
	if in == nil {
		return nil
	}
	out := new(RepositoryVolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scheduler) DeepCopyInto(out *Scheduler) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scheduler.
func (in *Scheduler) DeepCopy() *Scheduler {
	if in == nil {
		return nil
	}
	out := new(Scheduler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Strategy) DeepCopyInto(out *Strategy) {
	*out = *in
	in.Key.DeepCopyInto(&out.Key)
	out.Scheduler = in.Scheduler
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Strategy.
func (in *Strategy) DeepCopy() *Strategy {
	if in == nil {
		return nil
	}
	out := new(Strategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyDynamicKeySource) DeepCopyInto(out *StrategyDynamicKeySource) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyDynamicKeySource.
func (in *StrategyDynamicKeySource) DeepCopy() *StrategyDynamicKeySource {
	if in == nil {
		return nil
	}
	out := new(StrategyDynamicKeySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyKeySource) DeepCopyInto(out *StrategyKeySource) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Dynamic != nil {
		in, out := &in.Dynamic, &out.Dynamic
		*out = new(StrategyDynamicKeySource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyKeySource.
func (in *StrategyKeySource) DeepCopy() *StrategyKeySource {
	if in == nil {
		return nil
	}
	out := new(StrategyKeySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyKeySpec) DeepCopyInto(out *StrategyKeySpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyKeySpec.
func (in *StrategyKeySpec) DeepCopy() *StrategyKeySpec {
	if in == nil {
		return nil
	}
	out := new(StrategyKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestJob) DeepCopyInto(out *TestJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestJob.
func (in *TestJob) DeepCopy() *TestJob {
	if in == nil {
		return nil
	}
	out := new(TestJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestJobList) DeepCopyInto(out *TestJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TestJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestJobList.
func (in *TestJobList) DeepCopy() *TestJobList {
	if in == nil {
		return nil
	}
	out := new(TestJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestJobPodSpec) DeepCopyInto(out *TestJobPodSpec) {
	*out = *in
	in.PodSpec.DeepCopyInto(&out.PodSpec)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]TestJobVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]ArtifactSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestJobPodSpec.
func (in *TestJobPodSpec) DeepCopy() *TestJobPodSpec {
	if in == nil {
		return nil
	}
	out := new(TestJobPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestJobSpec) DeepCopyInto(out *TestJobSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.Tokens != nil {
		in, out := &in.Tokens, &out.Tokens
		*out = make([]TokenSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Repos != nil {
		in, out := &in.Repos, &out.Repos
		*out = make([]RepositorySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreSteps != nil {
		in, out := &in.PreSteps, &out.PreSteps
		*out = make([]PreStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostSteps != nil {
		in, out := &in.PostSteps, &out.PostSteps
		*out = make([]PostStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExportArtifacts != nil {
		in, out := &in.ExportArtifacts, &out.ExportArtifacts
		*out = make([]ExportArtifact, len(*in))
		copy(*out, *in)
	}
	in.Log.DeepCopyInto(&out.Log)
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(Strategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestJobSpec.
func (in *TestJobSpec) DeepCopy() *TestJobSpec {
	if in == nil {
		return nil
	}
	out := new(TestJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestJobStatus) DeepCopyInto(out *TestJobStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestJobStatus.
func (in *TestJobStatus) DeepCopy() *TestJobStatus {
	if in == nil {
		return nil
	}
	out := new(TestJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestJobTemplateSpec) DeepCopyInto(out *TestJobTemplateSpec) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestJobTemplateSpec.
func (in *TestJobTemplateSpec) DeepCopy() *TestJobTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TestJobTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestJobVolume) DeepCopyInto(out *TestJobVolume) {
	*out = *in
	in.TestJobVolumeSource.DeepCopyInto(&out.TestJobVolumeSource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestJobVolume.
func (in *TestJobVolume) DeepCopy() *TestJobVolume {
	if in == nil {
		return nil
	}
	out := new(TestJobVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestJobVolumeSource) DeepCopyInto(out *TestJobVolumeSource) {
	*out = *in
	in.VolumeSource.DeepCopyInto(&out.VolumeSource)
	if in.Repo != nil {
		in, out := &in.Repo, &out.Repo
		*out = new(RepositoryVolumeSource)
		**out = **in
	}
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(ArtifactVolumeSource)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(TokenVolumeSource)
		**out = **in
	}
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = new(LogVolumeSource)
		**out = **in
	}
	if in.Report != nil {
		in, out := &in.Report, &out.Report
		*out = new(ReportVolumeSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestJobVolumeSource.
func (in *TestJobVolumeSource) DeepCopy() *TestJobVolumeSource {
	if in == nil {
		return nil
	}
	out := new(TestJobVolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenSource) DeepCopyInto(out *TokenSource) {
	*out = *in
	if in.GitHubApp != nil {
		in, out := &in.GitHubApp, &out.GitHubApp
		*out = new(GitHubAppTokenSource)
		(*in).DeepCopyInto(*out)
	}
	if in.GitHubToken != nil {
		in, out := &in.GitHubToken, &out.GitHubToken
		*out = new(GitHubTokenSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenSource.
func (in *TokenSource) DeepCopy() *TokenSource {
	if in == nil {
		return nil
	}
	out := new(TokenSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenSpec) DeepCopyInto(out *TokenSpec) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenSpec.
func (in *TokenSpec) DeepCopy() *TokenSpec {
	if in == nil {
		return nil
	}
	out := new(TokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenVolumeSource) DeepCopyInto(out *TokenVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenVolumeSource.
func (in *TokenVolumeSource) DeepCopy() *TokenVolumeSource {
	if in == nil {
		return nil
	}
	out := new(TokenVolumeSource)
	in.DeepCopyInto(out)
	return out
}
