# permissions for end users to view testjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testjob-viewer-role
rules:
- apiGroups:
  - kubetest.io
  resources:
  - testjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubetest.io
  resources:
  - testjobs/status
  verbs:
  - get
