apiVersion: kubetest.io/v1
kind: TestJob
metadata:
  name: testjob
spec:
  git:
    checkout: false
  template:
    spec:
      containers:
        - name: test
          image: kubetest:v1
          command:
            - go
          args:
            - test
            - -v
            - ./
            - -run
            - $(TEST)
          workingDir: /go/src/github.com/goccy/kubetest/_examples
  distributedTest:
    containerName: test
    maxContainersPerPod: 6
    list:
      command:
        - go
      args:
        - test
        - -list
        - .
      pattern: ^Test
