name: test
on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup kind
      run: |
        make deploy
    - name: Run test
      run: |
        timeout 600 make test
    - name: Report coverage
      run: |
        bash <(curl -s https://codecov.io/bash)
