name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: build kubetest
        run: |
          go build -o kubetest ./cmd/kubetest
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: setup kind
        run: |
          make deploy
      - name: wait for available
        run: |
          make wait
      - name: Run test
        run: |
          timeout 800 make test
      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
