name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: checkout
        uses: actions/checkout@v2
      - name: build kubetest
        run: |
          go build -o kubetest ./cmd/kubetest
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: checkout
        uses: actions/checkout@v2
      - name: setup kind
        run: |
          make deploy
      - name: wait for available
        run: |
          make wait
      - name: Run test
        run: |
          timeout 800 make test
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
