name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup kind
      run: |
        make deploy
    - name: wait for available
      run: |
        make wait
    - name: Run test
      run: |
        timeout 800 make test
    - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
